Develop
nicolasmarino99/Boostrap-Newsweek pull request #1
Opened 2019-08-05 22:46 UTC by nicolasmarino99

2019-08-06 00:04 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-06 00:47 UTC, Torres-ssf commented
### Great job @nicolasmarino99 :clap:
You did nice work on this project, but we need to do some changes to make it in line with Microverse guidelines.

- [ ] Its a good practice to use the git-flow methodology. Check this [link](https://guides.github.com/introduction/flow/) You can try it on future projects. It's very easy and simple and will make you look like a PRO dev :thumbsup:

- [ ] Try to make the footer match the same style from the original page

- [ ] Your footer must contain the NW logo.

- [ ] Microverse guidelines require that your page must be responsive in smaller screens sizes. 


![Screenshot from 2019-08-05 21-32-36](https://user-images.githubusercontent.com/30977845/62503032-c9e3c300-b7c8-11e9-8d9a-004cccca5f4d.png)

![Screenshot from 2019-08-05 21-34-51](https://user-images.githubusercontent.com/30977845/62503060-e97aeb80-b7c8-11e9-9110-ab5b99791a6a.png)

![Screenshot from 2019-08-05 21-37-11](https://user-images.githubusercontent.com/30977845/62503130-38288580-b7c9-11e9-9be8-a7512ba2a059.png)

Please, kindly make these changes and submit for code review again. Happy coding

2019-08-07 00:41 UTC, Ispirett requested changes
Hey, @nicolasmarino99  great work with the changes requested by @Torres-ssf you are doing a fantastic job :1st_place_medal: . There are just a few key things that need a little addressing

- [x] A round **800px* or so change the width to col-md-12 or col-sm-12 or get the set the width of the itesm to 100%

![bstrap](https://user-images.githubusercontent.com/38801423/62586295-f6601380-b88a-11e9-8f03-810bc43e6169.png)


**The orginal site**
![bstrap2](https://user-images.githubusercontent.com/38801423/62586167-79cd3500-b88a-11e9-81d5-975e3658d9b9.png)

- [x]  **html errors**
There are a lot of HTML errors on this page use this tool and please correct them https://validator.w3.org/

Send for another review when finished.

2019-08-07 00:41 UTC, Ispirett commented on index.html
> +        <div class="row" id="bar-with-anchors">
**[Optional] This is not required for your project to be approved but I encourage you to consider.**
- [ ] Try using a  `<nav>` `<ul>` tag and `<li>`

2019-08-08 00:53 UTC, Ispirett approved these changes
Great work with changes made. you can merge your project and submit you complete form :+1: .

**[ Optional] I strongly like advise you to make these changes it will make your project look more professional.**

![756](https://user-images.githubusercontent.com/38801423/62667089-22939700-b954-11e9-8859-511a10f4439d.png)

![750-2](https://user-images.githubusercontent.com/38801423/62667097-2e7f5900-b954-11e9-84f7-630b2a3bdbaa.png)

- [ ] Don't let the text wrap around the images at this resolution and below, around 750px. instead, let the images fill the screen and the text be completely under the images.

- [ ] Also for links it's better to use `<nav> ul and li `tags.

- [ ] Also using article tags instead of divs is a good practice for all the articles listed on the page.

2019-08-08 22:26 UTC, merged